// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zfbOBOa3BDgNtD11Yja1S9UMKyVps38',
    appId: '1:414657098182:web:23ff0ab6d4cffefe77c2c7',
    messagingSenderId: '414657098182',
    projectId: 'authjardinpro-939ba',
    authDomain: 'authjardinpro-939ba.firebaseapp.com',
    storageBucket: 'authjardinpro-939ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLMh4J1Wj8lk3rCtuizy7lesqJj78yUrE',
    appId: '1:414657098182:android:da2f627a96f4916c77c2c7',
    messagingSenderId: '414657098182',
    projectId: 'authjardinpro-939ba',
    storageBucket: 'authjardinpro-939ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu7OQv5inERXgZd-1ik1ggYSHeb23um4I',
    appId: '1:414657098182:ios:d71456d22461e3ca77c2c7',
    messagingSenderId: '414657098182',
    projectId: 'authjardinpro-939ba',
    storageBucket: 'authjardinpro-939ba.appspot.com',
    iosBundleId: 'com.example.jardinPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu7OQv5inERXgZd-1ik1ggYSHeb23um4I',
    appId: '1:414657098182:ios:d71456d22461e3ca77c2c7',
    messagingSenderId: '414657098182',
    projectId: 'authjardinpro-939ba',
    storageBucket: 'authjardinpro-939ba.appspot.com',
    iosBundleId: 'com.example.jardinPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5zfbOBOa3BDgNtD11Yja1S9UMKyVps38',
    appId: '1:414657098182:web:d5ae847e965f798e77c2c7',
    messagingSenderId: '414657098182',
    projectId: 'authjardinpro-939ba',
    authDomain: 'authjardinpro-939ba.firebaseapp.com',
    storageBucket: 'authjardinpro-939ba.appspot.com',
  );
}
